username: 'Mila88'
password: '5c36b9ebe1'
address: 'https://test-stand.gb.ru/'
driver_path: 'C:\Users\Administrator\PycharmProjects\pythonProject\less2\chromedriver.exe'
sleep_time: 2
url_login: 'https://test-stand.gb.ru/gateway/login'
url_posts: 'https://test-stand.gb.ru/api/posts'
title: 'New title'
description: 'New description'
content: 'content content content'


